# This is a basic workflow to help you get started with Actions

name: CI1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0/2 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: do some test idk
      run: |
        echo $GITHUB_WORKSPACE
        sudo echo hello >> $GITHUB_WORKSPACE/test_file
    
#     - name: run test file
#       run: sudo python ../../API/APITest.py
    
    # Runs a single command using the runners shell
    - name: Run updater
      run: sudo python $GITHUB_WORKSPACE/API/OtherTools.py -ur
